# Generated by Django 2.2.5 on 2020-02-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/tree')),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alignement_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('algo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FastQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='ngs/fastq/')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/fasta')),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence_fasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGene', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('nomEspece', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/genome')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngs.Request')),
            ],
        ),
        migrations.CreateModel(
            name='FastQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/fastqc/')),
                ('fastq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngs.FastQ')),
            ],
        ),
        migrations.AddField(
            model_name='fastq',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngs.Request'),
        ),
        migrations.CreateModel(
            name='Arbre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newick', models.TextField()),
                ('alignement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngs.Alignement_result')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/annotations')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngs.Request')),
            ],
        ),
        migrations.AddField(
            model_name='alignement_result',
            name='Sequences',
            field=models.ManyToManyField(blank=True, related_name='Alignements', to='ngs.Sequence_fasta'),
        ),
        migrations.AddField(
            model_name='alignement_result',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngs.User'),
        ),
    ]
