# Generated by Django 2.2.5 on 2020-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/tree')),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ngs/fasta')),
                ('mail', models.EmailField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Alignment',
        ),
    ]
